name: Live Deployment

on:
  workflow_dispatch:
  
# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cscp-hosteurope
    env: 
      VITE_PUBLIC_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Build site Frontend
        run: npm run build
      - name: Setup Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          args: "--ignore-platform-reqs --optimize-autoloader --no-dev"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment
          include-hidden-files: true
          retention-days: 5
          path: |
            build/
            site/
            vendor/
            kirby/
            content/
            index.php
            .htaccess
            .lftpexclude

  deploy:
    needs: build
    environment: cscp-hosteurope
    runs-on: ubuntu-latest
    env:
      FTPS_HOST: ${{ secrets.FTPS_HOST }}
      FTPS_USER: ${{ secrets.FTPS_USER }}
      FTPS_PASSWORD: ${{ secrets.FTPS_PASSWORD }}
      FTPS_FOLDER: ${{ secrets.FTPS_FOLDER }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment
          path: dist
      - name: Install lftp
        run: sudo apt install -y lftp
      - run: ls -la
      - run: lftp -v -e "set ftp:ssl-auth TLS; set ftp:ssl-force true; set ftp:ssl-protect-list yes; set ftp:ssl-protect-data yes; set ftp:ssl-protect-fxp yes; set ssl:verify-certificate no; set ftp:list-options -a; set net:timeout 5; set net:max-retries 3; set net:reconnect-interval-base 5; open $FTPS_HOST; user $FTPS_USER $FTPS_PASSWORD; mirror --exclude-glob-from ./dist/.lftpexclude --reverse ./dist/ $FTPS_FOLDER/; bye"
